### ISSUE TITLE
mongo URL

### ISSUE THREAD

**Issue by andymcollins** [toystars/node-elasticsearch-sync#1]
When i run 

ESMongoSync.init("mongodb://localhost:27017/db","localhost:9200", finalCallBack, watcherArray, batchCount);

i get this error
throw new TypeError("Parameter 'url' must be a string, not " + typeof url);

**Comment by toystars** [comment]
@andymcollins, it is a bug when trying to connect to mongoDB using only environment variables, instead of checking if the mongo url is set in init().It has been fixed in PR #3

**Comment by andymcollins** [comment]
Great Thank you
