### ISSUE TITLE
ESMongoSync: Incorrect argument count in init function

### ISSUE THREAD

**Issue by ghost** [toystars/node-elasticsearch-sync#10]
I am calling the function as :

ESMongoSync.init(null, null, null, watchers, 500);

Please assist if its wrong.

**Comment by toystars** [comment]
In the new release, you only call the `init` function with two arguments like so: `ESMongoSync.init(watchers, null)`, then you define the following environment variables: `MONGO_OPLOG_URL`, `MONGO_DATA_URL`, `ELASTIC_SEARCH_URL`, `BATCH_COUNT`. That should get you going...

**Comment by ghost** [comment]
Works fine. Thank you

**Comment by nuest** [comment]
Could you update the examples in the README, please?

**Comment by nuest** [comment]
My apologies, I just oversaw the "example for version prior to 1.0.0" in the headline.
