### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by ghost** [toystars/node-elasticsearch-sync#11]
> ESMongoSync: Oplog tailing connection successful.

<--- Last few GCs --->

```
6182 ms: Scavenge 1412.6 (1457.8) -> 1412.6 (1457.8) MB, 4.5 / 0 ms (+ 6.4 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
6360 ms: Mark-sweep 1412.6 (1457.8) -> 1412.6 (1457.8) MB, 178.4 / 0 ms (+ 21.1 ms in 7 steps since start of marking, biggest step 6.4 ms) [last resort gc].
6544 ms: Mark-sweep 1412.6 (1457.8) -> 1412.6 (1457.8) MB, 184.5 / 0 ms [last resort gc].
```

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2aecf56e3ac1 <JS Object>
    1: /\* anonymous _/(aka /_ anonymous */) [/home/abhilash.bolla/Learning/elasticsearch_query_example/node_modules/mongodb/node_modules/bson/lib/bson/parser/deserializer.js:~39] [pc=0x1c5ae0e609d2](this=0x2aecf5604189 <undefined>,buffer=0x25ef6ed1ec91 <an Uint8Array with map 0x36a53f052e1>,index=2393118,options=0x25ef6ed1ece1 <an Object with map 0x36a53f1b549>,isArray=0x2aecf5604231 <true)
 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)

Getting this error.

**Comment by toystars** [comment]
How big are the documents in your database and what version of node are you using?

**Comment by toystars** [comment]
And I believe that error was thrown due to node running out of memory. You can increase the memory allocated to node and try again. [This](http://www.codingdefined.com/2015/10/how-to-solve-process-out-of-memory.html) might help.

**Comment by ghost** [comment]
node v5.12.0.
Size of each document is around 44.122 Kb. and there are 10k documents in the collection.
I have elasticsearch, mongo, node all running on JVM and my RAM is only 8GB, of which I have allocated 4GB heap size for elasticsearch itself

**Comment by ghost** [comment]
I do this.. and its get stuck. Why does the console have "undefined" logged?

> $ node --max-old-space-size=2048 elastic-sync.js
> ESMongoSync: Connected to ElasticSearch successfully!
> ESMongoSync: Connected to MONGO server successfully.
> ESMongoSync: Beginning batch creation
> ESMongoSync: Processing watchers on priority level  0
> ESMongoSync: Processing  patents  collection
> ESMongoSync: Oplog tailing connection successful.
> ESMongoSync: Batch creation complete. Processing...
> ESMongoSync: Number of documents in batch -  500
> undefined

**Comment by toystars** [comment]
Create a gist with your code that uses the package and let me try and reproduce the error. That will make debugging easier

**Comment by ghost** [comment]
https://gist.github.com/abhilashbolla-innoplexus/7ccd7d4e67d3ec3d6874880559e42b33

here you go.!!

**Comment by toystars** [comment]
So I used your exact config but changed some things like database name, etc. And here are my results...

![screenshot from 2016-09-07 08-27-28](https://cloud.githubusercontent.com/assets/16062709/18303465/217c3b18-74d5-11e6-954d-066866604538.png)

Below is the config I used...
![screenshot from 2016-09-07 08-27-41](https://cloud.githubusercontent.com/assets/16062709/18303492/3cee5944-74d5-11e6-8143-45d87e1bfd01.png)

As you can see, it works as it should, without throwing undefined.

One thing to note though, the process won't exit unless you exit it yourself as it is meant to listen to any CRUD event in mongoDB, so it will keep running for as long as required.
