### ISSUE TITLE
Improved logging

### ISSUE THREAD

**Issue by nuest** [toystars/node-elasticsearch-sync#12]
Hi there. Very useful package you have there! Would you be interested in a contribution with extended logging statements using the `debug` module (see [https://www.npmjs.com/package/debug](https://www.npmjs.com/package/debug))? I've had to hunt down an issue in my usage of the code and some extended configurable logging would have helped.

**Comment by toystars** [comment]
Sure that would be awesome.

**Comment by nuest** [comment]
![upload_11_11_2016_at_3_16_25_pm](https://cloud.githubusercontent.com/assets/1325054/20217839/0fbf78f6-a822-11e6-824b-972f13636628.png)
