### ISSUE TITLE
Bug in selecting collection name

### ISSUE THREAD

**Issue by nuest** [toystars/node-elasticsearch-sync#7]
I have an issue with `collection name != type name`, and I think it is down to this line

https://github.com/toystars/node-elasticsearch-sync/blob/master/index.js#L64

Should that not do something like `currentCollectionName = document.collection` ?

**Comment by toystars** [comment]
As it stands right now, the name of every Mongo collection to be synced in ES has to be the name used in ES as type name. This might be configurable in nearest future...

**Comment by nuest** [comment]
I understand.

The watcher configuration and examples show using two values, which could be interpreted as them being independent. I suggest to mention this limitation in the examples, or to throw an error when the values are different.

Thanks for the quick reply!
